# Generated by Django 4.2.6 on 2023-11-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0002_rename_ingretientes_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens/'),
        ),
    ]
